# Generated by Django 3.2.6 on 2021-08-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('empolyername', models.CharField(max_length=100)),
                ('empolyeremail', models.CharField(max_length=100)),
            ],
        ),
    ]
